[package]
name = "sea-bunny"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.17", features = ["default", "serde"] }
anyhow = "1.0"
serde = { version = "1.0.229", features = ["derive", "std"] }
reqwest = { version = "0.13.4", features = ["json"] }
tokio = { version = "1.53.1", features = ["full"] }

[build-dependencies]
slint-build = "1.17"
