import {
    VerticalBox,
    ScrollView,
    ListView,
    Palette,
    StyleMetrics,
    ProgressIndicator,
    Spinner,
} from "std-widgets.slint";
import { ConversationView } from "conversation.slint";
import { UIConversationItem } from "../../models/conversation-item.slint";
import { ToolButton } from "../../components/tool-button.slint";
import { SidebarButton } from "./sidebar-btn.slint";
import { ConversationItem } from "./conversation-item.slint";
import { Button } from "../../components/button.slint";
import { LineEdit } from "../../components/lineedit.slint";

export component AppWindow inherits Window {
    min-width: 800px;
    min-height: 600px;
    title: @tr("Sea Bunny");

    in property <[UIConversationItem]> conversations: [
        {
            name: "Konijntje x Sea",
            last_message: "Always good to meet another crazy girl like me!",
            last_message_time: "12:34",
            unread_count: 2,
        }
    ];
    in-out property <int> active-conversation-index: 0;
    in property <bool> is-loading: false;
    in property <string> loading-status;

    HorizontalLayout {
        Rectangle {
            width: 280px;
            background: Palette.alternate-background;

            VerticalBox {
                Rectangle {
                    HorizontalLayout {
                        spacing: StyleMetrics.layout-spacing;

                        LineEdit {
                            placeholder-text: @tr("Search...");
                        }

                        ToolButton {
                            icon: @image-url("../../assets/ic_fluent_filter_24_filled.svg");
                        }

                        ToolButton {
                            icon: @image-url("../../assets/ic_fluent_chat_add_24_filled.svg");
                        }
                    }
                }

                SidebarButton {
                    text: @tr("Home");
                    icon: @image-url("../../assets/ic_fluent_home_24_filled.svg");
                    active: active-conversation-index == -1;

                    clicked => {
                        active-conversation-index = -1;
                    }
                }

                SidebarButton {
                    text: @tr("Threads");
                    icon: @image-url("../../assets/ic_fluent_chat_multiple_24_filled.svg");
                    active: active-conversation-index == -2;

                    clicked => {
                        active-conversation-index = -2;
                    }
                }

                Rectangle {
                    height: 1px;
                    background: Palette.border;
                }

                // conversation item list
                ListView {

                    for conversation[idx] in conversations: ConversationItem {
                        conversation: conversation;
                        active: active-conversation-index == idx;

                        clicked => {
                            active-conversation-index = idx;
                        }
                    }
                }

                Rectangle {
                    height: 1px;
                    background: Palette.border;
                }

                SidebarButton {
                    text: @tr("App settings");
                    icon: @image-url("../../assets/ic_fluent_settings_24_filled.svg");
                }
            }
        }

        Rectangle {
            width: 1px;
            background: Palette.border;
        }

        if conversations.length > 0 && active-conversation-index >= 0: ConversationView {
            horizontal-stretch: 1;
            conversation: conversations[active-conversation-index];
        }
    }

    if root.is-loading: Rectangle {
        background: Colors.black.transparentize(0.5);

        VerticalLayout {
            alignment: LayoutAlignment.center;
            cross-axis-alignment: CrossAxisAlignment.center;
            spacing: 24px;

            Spinner {
                indeterminate: true;
                height: 48px;
                width: self.height;
            }

            Text {
                text: root.loading-status;
            }
        }
    }
}
