import {
    VerticalBox,
    LineEdit,
    ScrollView,
    ListView,
    Palette,
    StyleMetrics,
    Button,
} from "std-widgets.slint";
import { ConversationView } from "conversation.slint";
import { UIConversationItem } from "../../models/conversation-item.slint";
import { ToolButton } from "../../components/tool-button.slint";

component SidebarButton inherits Rectangle {
    in property <string> text;
    in property <image> icon;
    in property <bool> active: false;

    callback clicked <=> touch-area.clicked;

    border-radius: 4px;

    states [
        hover when touch-area.has-hover: {
            root.background: Palette.foreground.transparentize(0.9);
        }
    ]

    HorizontalLayout {

        Rectangle {
            width: 3px;
            background: active ? Palette.accent-background : Colors.transparent;
            border-radius: 1px;
        }

        HorizontalLayout {
            spacing: StyleMetrics.layout-spacing;
            padding: StyleMetrics.layout-spacing / 2;

            Image {
                source: root.icon;
                width: 24px;
                height: 24px;
            }

            Text {
                text: root.text;
                vertical-alignment: TextVerticalAlignment.center;
            }
        }
    }

    touch-area := TouchArea { }
}

component ConversationItem inherits Rectangle {
    in property <UIConversationItem> conversation;
    in property <bool> active: false;

    callback clicked <=> touch-area.clicked;

    border-radius: 4px;

    states [
        hover when touch-area.has-hover: {
            root.background: Palette.foreground.transparentize(0.9);
        }
    ]

    HorizontalLayout {
        spacing: StyleMetrics.layout-spacing / 2;
        padding-top: StyleMetrics.layout-spacing;
        padding-bottom: StyleMetrics.layout-spacing;
        padding-right: StyleMetrics.layout-spacing / 2;

        Rectangle {
            width: 3px;
            background: active ? Palette.accent-background : Colors.transparent;
            border-radius: 1px;
        }

        Rectangle {
            width: 1px;
        }

        Rectangle {
            height: 40px;
            width: 40px;

            background: Palette.accent-background;
            border-radius: 20px;

            Image {
                source: conversation.avatar;
                height: 40px;
                width: 40px;
            }
        }

        VerticalLayout {
            Text {
                text: conversation.name;
            }

            Text {
                text: conversation.last-message;
                overflow: TextOverflow.elide;
            }
        }
    }

    touch-area := TouchArea { }
}

export component AppWindow inherits Window {
    min-width: 800px;
    min-height: 600px;
    title: @tr("Sea Bunny");

    in property <[UIConversationItem]> conversations: [
        {
            name: "Konijntje x Sea",
            last_message: "Always good to meet another crazy girl like me!",
            last_message_time: "12:34",
            unread_count: 2,
        }
    ];
    in-out property <int> active-conversation-index: 0;

    HorizontalLayout {
        Rectangle {
            width: 280px;
            background: Palette.alternate-background;

            VerticalBox {
                Rectangle {
                    HorizontalLayout {
                        spacing: StyleMetrics.layout-spacing;

                        LineEdit {
                            placeholder-text: @tr("Search...");
                        }

                        ToolButton {
                            icon: @image-url("../../assets/ic_fluent_filter_24_filled.svg");
                        }

                        ToolButton {
                            icon: @image-url("../../assets/ic_fluent_chat_add_24_filled.svg");
                        }
                    }
                }

                SidebarButton {
                    text: @tr("Home");
                    icon: @image-url("../../assets/ic_fluent_home_24_filled.svg");
                    active: active-conversation-index == -1;

                    clicked => {
                        active-conversation-index = -1;
                    }
                }

                SidebarButton {
                    text: @tr("Threads");
                    icon: @image-url("../../assets/ic_fluent_chat_multiple_24_filled.svg");
                    active: active-conversation-index == -2;

                    clicked => {
                        active-conversation-index = -2;
                    }
                }

                Rectangle {
                    height: 1px;
                    background: Palette.border;
                }

                // conversation item list
                ListView {

                    for conversation[idx] in conversations: ConversationItem {
                        conversation: conversation;
                        active: active-conversation-index == idx;

                        clicked => {
                            active-conversation-index = idx;
                        }
                    }
                }

                Rectangle {
                    height: 1px;
                    background: Palette.border;
                }

                SidebarButton {
                    text: @tr("App settings");
                    icon: @image-url("../../assets/ic_fluent_settings_24_filled.svg");
                }
            }
        }

        Rectangle {
            width: 1px;
            background: Palette.border;
        }

        if conversations.length > 0 && active-conversation-index >= 0: ConversationView {
            horizontal-stretch: 1;
            conversation: conversations[active-conversation-index];
        }
    }
}
