import {
    VerticalBox,
    LineEdit,
    ScrollView,
    ListView,
    Palette,
    StyleMetrics,
    Button,
} from "std-widgets.slint";
import { ConversationView } from "conversation.slint";
import { UIConversationItem } from "../../models/conversation-item.slint";
import { ToolButton } from "../../components/tool-button.slint";

export component SidebarButton inherits Rectangle {
    in property <string> text;
    in property <image> icon;
    in property <bool> active: false;

    callback clicked <=> touch-area.clicked;

    border-radius: 4px;

    states [
        hover when touch-area.has-hover: {
            root.background: Palette.foreground.transparentize(0.9);
        }
    ]

    HorizontalLayout {

        Rectangle {
            width: 3px;
            background: active ? Palette.accent-background : Colors.transparent;
            border-radius: 1px;
        }

        HorizontalLayout {
            spacing: StyleMetrics.layout-spacing;
            padding: StyleMetrics.layout-spacing / 2;

            Image {
                source: root.icon;
                width: 24px;
                height: 24px;
            }

            Text {
                text: root.text;
                vertical-alignment: TextVerticalAlignment.center;
            }
        }
    }

    touch-area := TouchArea { }
}
