import {
    HorizontalBox,
    VerticalBox,
    StyleMetrics,
    Palette,
} from "std-widgets.slint";
import { Button } from "../../components/button.slint";
import { LineEdit } from "../../components/lineedit.slint";

export component FirstTimeSetupWindow inherits Window {
    in property <bool> has-error: false;
    in property <string> message: @tr("First time setup");

    width: 400px;
    height: 460px;
    title: @tr("First Time Setup");

    callback connect(server: string);

    VerticalLayout {

        HorizontalLayout {
            padding: 40px;
            padding-bottom: 20px;
            alignment: LayoutAlignment.center;
            cross-axis-alignment: CrossAxisAlignment.center;

            Rectangle {
                height: 240px;
                Image {
                    source: Palette.color-scheme == ColorScheme.dark ? @image-url("../../assets/logo-dark.svg") : @image-url("../../assets/logo-light.svg");
                    height: parent.height;
                    image-fit: ImageFit.contain;
                }
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }

        VerticalBox {

            HorizontalBox {
                Text {
                    text: message;
                    horizontal-alignment: center;
                    color: has-error ? Colors.red : Palette.foreground.transparentize(0.4);
                }
            }

            GridLayout {
                spacing: StyleMetrics.layout-spacing;

                Row {
                    Text {
                        text: @tr("Nextcloud server:");
                        vertical-alignment: TextVerticalAlignment.center;
                    }

                    server-input := LineEdit {
                        placeholder-text: @tr("https://cloud.example.com");
                    }
                }
            }
        }

        HorizontalBox {
            alignment: LayoutAlignment.center;

            Button {
                text: @tr("Connect");
                primary: true;
                clicked => {
                    root.connect(server-input.text);
                }
            }
        }
    }
}
