import {
    GridBox,
    HorizontalBox,
    LineEdit,
    Button,
    VerticalBox,
} from "std-widgets.slint";
export component LoginWindow inherits Window {
    width: 400px;
    height: 160px;
    title: @tr("SeaBuny Login");

    callback login(username: string, password: string);
    callback exit();

    VerticalBox {
        Text {
            text: @tr("Please login to your Nextcloud server.");
        }

        HorizontalLayout {
            username-input := LineEdit {
                placeholder-text: @tr("username");
            }
        }

        HorizontalLayout {

            password-input := LineEdit {
                placeholder-text: @tr("password");
                input-type: InputType.password;
            }
        }

        HorizontalLayout {
            alignment: LayoutAlignment.end;

            Button {
                text: @tr("Exit");
                clicked => {
                    exit();
                }
            }

            Button {
                text: @tr("Login");
                primary: true;
                clicked => {
                    login(username-input.text, password-input.text);
                }
            }
        }
    }
}
